import { StyleSheet } from "react-native";
import { theme } from "../../styles/theme";

export const styles = StyleSheet.create({
  contentContainer: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 24,
  },
  pageTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 4,
  },
  pageSubtitle: {
    color: "#8E8E93",
    fontSize: 14,
    marginBottom: 14,
    lineHeight: 20,
  },
  vehicleBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "flex-start",
    backgroundColor: "rgba(74, 222, 158, 0.1)",
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginBottom: 18,
  },
  vehicleBadgeText: {
    color: theme.colors.accent.primary,
    fontSize: 13,
    fontWeight: "500",
  },
  draftBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "flex-start",
    backgroundColor: "rgba(210, 153, 34, 0.12)",
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(210, 153, 34, 0.2)",
  },
  draftBadgeText: {
    color: "#D29922",
    fontSize: 13,
    fontWeight: "500",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  section: {
    backgroundColor: "#1A1C1E",
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    gap: 14,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: {
    color: theme.colors.accent.primary,
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  sectionMeta: {
    color: "#8E8E93",
    fontSize: 12,
    fontWeight: "500",
  },
  field: {
    gap: 6,
  },
  label: {
    color: "#8E8E93",
    fontSize: 13,
  },
  input: {
    backgroundColor: "#232527",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    color: "#FFFFFF",
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 15,
  },
  textarea: {
    minHeight: 96,
    textAlignVertical: "top",
  },
  hint: {
    color: "#8E8E93",
    fontSize: 12,
    lineHeight: 17,
  },
  workItem: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    padding: 12,
    gap: 10,
  },
  workItemHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  workItemTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  workItemIndex: {
    width: 24,
    height: 24,
    borderRadius: 8,
    backgroundColor: theme.colors.accent.dark,
    alignItems: "center",
    justifyContent: "center",
  },
  workItemIndexText: {
    color: theme.colors.accent.primary,
    fontSize: 12,
    fontWeight: "700",
  },
  workItemTitle: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  removeWorkButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 6,
  },
  removeWorkText: {
    color: "#F85149",
    fontSize: 12,
    fontWeight: "600",
  },
  removeWorkTextDisabled: {
    color: "#6E7681",
  },
  addWorkButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: theme.colors.accent.dark,
    borderRadius: 12,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: "rgba(74, 222, 158, 0.15)",
    borderStyle: "dashed",
  },
  addWorkButtonText: {
    color: theme.colors.accent.primary,
    fontSize: 14,
    fontWeight: "600",
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 4,
    borderTopWidth: 1,
    borderTopColor: "rgba(74, 222, 158, 0.15)",
    marginTop: 4,
  },
  totalLabel: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
  },
  totalPrice: {
    color: theme.colors.accent.primary,
    fontSize: 17,
    fontWeight: "700",
  },
  actionsSection: {
    gap: 10,
    marginTop: 4,
    marginBottom: 8,
  },
  saveButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: theme.colors.interactive.primary,
    borderRadius: 14,
    paddingVertical: 14,
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveButtonText: {
    color: theme.colors.text.inverse,
    fontSize: 15,
    fontWeight: "600",
  },
  cancelButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: theme.colors.accent.dark,
    borderRadius: 14,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "rgba(74, 222, 158, 0.15)",
  },
  cancelButtonText: {
    color: theme.colors.accent.primary,
    fontSize: 15,
    fontWeight: "600",
  },
});
