services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: Main
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - mainhub-network

  mainhub-api:
    build:
      context: ../../Services/Main/MainHub.Api
      dockerfile: Dockerfile
    container_name: mainhub-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - MongoDbSettings__ConnectionString=mongodb://admin:admin123@mongodb:27017
      - MongoDbSettings__DatabaseName=Main
      - MongoDbSettings__UserCollectionName=Users
      - MongoDbSettings__VehicleCollectionName=Vehicles
      - MongoDbSettings__ServiceHistoryCollectionName=ServiceHistories
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    networks:
      - mainhub-network

  expo-mobile:
    build:
      context: ../../apps/Mobile
      dockerfile: Dockerfile
    container_name: expo-mobile
    volumes:
      - ../../apps/Mobile:/app
      - /app/node_modules
    ports:
      - "8082:8082"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    stdin_open: true
    tty: true
    command: npm start

  admin-web-ui:
    build:
      context: ../../apps/AdminWebUi
      dockerfile: Dockerfile
    container_name: admin-web-ui
    volumes:
      - ../../apps/AdminWebUi:/app
      - /app/node_modules
    ports:
      - "5100:5100"
    environment:
        - NODE_ENV=development
        - VITE_PORT=5100
    stdin_open: true
    tty: true
    command: npm run dev

volumes:
  mongodb_data:

networks:
  mainhub-network:
    driver: bridge
