import { StyleSheet } from "react-native";
import { theme } from "../../styles/theme";

export const styles = StyleSheet.create({
  panel: {
    flex: 1,
    position: "relative",
  },
  scroll: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingBottom: 28,
  },
  scrollContent: {
    paddingTop: 16,
  },
  pageTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 4,
  },
  pageSubtitle: {
    color: "#8E8E93",
    fontSize: 14,
    marginBottom: 18,
    lineHeight: 20,
  },
  sessionCard: {
    backgroundColor: "#1A1C1E",
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    gap: 12,
  },
  sessionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  sessionIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: theme.colors.accent.dark,
    alignItems: "center",
    justifyContent: "center",
  },
  sessionInfo: {
    flex: 1,
    gap: 3,
  },
  sessionServiceName: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  sessionVehicle: {
    color: "#8E8E93",
    fontSize: 13,
  },
  liveBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
    backgroundColor: "rgba(74, 222, 158, 0.1)",
    borderRadius: 20,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  liveDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: theme.colors.accent.primary,
  },
  liveBadgeText: {
    color: theme.colors.accent.primary,
    fontSize: 12,
    fontWeight: "600",
  },
  progressSection: {
    backgroundColor: "#1A1C1E",
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    gap: 10,
  },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  progressTitle: {
    color: theme.colors.accent.primary,
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  progressPercent: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  progressTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 4,
    backgroundColor: theme.colors.accent.primary,
  },
  contextCard: {
    backgroundColor: "rgba(74, 222, 158, 0.08)",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(74, 222, 158, 0.15)",
  },
  contextText: {
    color: "#E8FFF5",
    fontSize: 14,
    lineHeight: 20,
  },
  timelineSection: {
    backgroundColor: "#1A1C1E",
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  timelineTitle: {
    color: theme.colors.accent.primary,
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 16,
  },
  timelineItem: {
    flexDirection: "row",
    gap: 12,
    minHeight: 52,
  },
  timelineRail: {
    width: 28,
    alignItems: "center",
  },
  timelineDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#232527",
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  timelineDotCompleted: {
    backgroundColor: theme.colors.accent.dark,
    borderColor: theme.colors.accent.primary,
  },
  timelineDotCurrent: {
    backgroundColor: theme.colors.accent.primary,
    borderColor: theme.colors.accent.primary,
  },
  timelineDotUpcoming: {
    backgroundColor: "#232527",
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  timelineDotEmoji: {
    fontSize: 12,
  },
  timelineLine: {
    flex: 1,
    width: 2,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    marginVertical: 4,
  },
  timelineLineCompleted: {
    backgroundColor: "rgba(74, 222, 158, 0.35)",
  },
  timelineContent: {
    flex: 1,
    paddingBottom: 16,
  },
  timelineContentLast: {
    paddingBottom: 0,
  },
  timelineStepTitle: {
    color: "#8E8E93",
    fontSize: 14,
    fontWeight: "500",
    marginTop: 4,
  },
  timelineStepTitleCompleted: {
    color: "#B0B0B0",
  },
  timelineStepTitleCurrent: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
  timelineStepTitleUpcoming: {
    color: "#6E7681",
  },
  estimateCard: {
    backgroundColor: "#1A1C1E",
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    gap: 10,
  },
  estimateTitle: {
    color: theme.colors.accent.primary,
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  estimateRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.06)",
  },
  estimateRowFirst: {
    borderTopWidth: 0,
    paddingTop: 0,
  },
  estimateItemTitle: {
    color: "#FFFFFF",
    fontSize: 14,
    flex: 1,
  },
  estimateItemPrice: {
    color: "#8E8E93",
    fontSize: 14,
    fontWeight: "500",
  },
  estimateTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 12,
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: "rgba(74, 222, 158, 0.15)",
  },
  estimateTotalLabel: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
  },
  estimateTotalPrice: {
    color: theme.colors.accent.primary,
    fontSize: 17,
    fontWeight: "700",
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: theme.colors.interactive.primary,
    borderRadius: 14,
    paddingVertical: 14,
    marginBottom: 10,
  },
  primaryButtonText: {
    color: theme.colors.text.inverse,
    fontSize: 15,
    fontWeight: "600",
  },
  secondaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: theme.colors.accent.dark,
    borderRadius: 14,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "rgba(74, 222, 158, 0.15)",
    marginBottom: 10,
  },
  secondaryButtonText: {
    color: theme.colors.accent.primary,
    fontSize: 15,
    fontWeight: "600",
  },
  emptyCard: {
    backgroundColor: "#1A1C1E",
    borderRadius: 16,
    padding: 32,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    borderStyle: "dashed",
    gap: 10,
  },
  emptyTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  emptyText: {
    color: "#8E8E93",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },
  demoStrip: {
    backgroundColor: "#232527",
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    gap: 8,
  },
  demoStripTitle: {
    color: "#8E8E93",
    fontSize: 11,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  demoChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  demoChip: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: "rgba(255, 255, 255, 0.06)",
  },
  demoChipActive: {
    backgroundColor: theme.colors.accent.dark,
    borderWidth: 1,
    borderColor: "rgba(74, 222, 158, 0.25)",
  },
  demoChipText: {
    color: "#B0B0B0",
    fontSize: 11,
    fontWeight: "500",
  },
  demoChipTextActive: {
    color: theme.colors.accent.primary,
    fontWeight: "600",
  },
});
