import { StyleSheet } from "react-native";
import { theme } from "../../styles/theme";

export const styles = StyleSheet.create({
  panel: {
    flex: 1,
    position: "relative",
  },
  scroll: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingBottom: 28,
  },
  scrollContent: {
    paddingTop: 16,
  },
  pageTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 4,
  },
  pageSubtitle: {
    color: "#8E8E93",
    fontSize: 14,
    marginBottom: 18,
  },
  section: {
    backgroundColor: "#1A1C1E",
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  sectionTitle: {
    color: theme.colors.accent.primary,
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  sectionAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: theme.colors.accent.dark,
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  sectionActionText: {
    color: theme.colors.accent.primary,
    fontSize: 12,
    fontWeight: "600",
  },
  vehiclePickerWrapper: {
    marginBottom: 14,
  },
  vehiclePicker: {
    backgroundColor: "#1A1C1E",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  vehiclePickerOpen: {
    borderColor: "rgba(74, 222, 158, 0.28)",
    backgroundColor: "#1C1F21",
  },
  vehiclePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    gap: 12,
  },
  vehiclePickerChevron: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  vehiclePickerChevronOpen: {
    backgroundColor: "rgba(74, 222, 158, 0.12)",
  },
  vehicleThumb: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: "#232527",
  },
  vehicleThumbPlaceholder: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: theme.colors.accent.dark,
    alignItems: "center",
    justifyContent: "center",
  },
  vehiclePickerInfo: {
    flex: 1,
    gap: 2,
  },
  vehiclePickerName: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  vehiclePickerPlate: {
    color: "#8E8E93",
    fontSize: 13,
  },
  vehiclePickerMenu: {
    backgroundColor: "#232527",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(74, 222, 158, 0.18)",
    paddingTop: 10,
    paddingBottom: 6,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    overflow: "hidden",
  },
  vehiclePickerMenuPortal: {
    position: "absolute",
    zIndex: 100,
    elevation: 100,
  },
  vehiclePickerMenuTitle: {
    color: "#8E8E93",
    fontSize: 11,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    paddingHorizontal: 14,
    marginBottom: 6,
  },
  vehiclePickerMenuList: {
    maxHeight: 260,
  },
  vehiclePickerItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginHorizontal: 6,
    marginBottom: 2,
    gap: 12,
    borderRadius: 10,
  },
  vehiclePickerItemActive: {
    backgroundColor: "rgba(74, 222, 158, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(74, 222, 158, 0.2)",
  },
  vehiclePickerItemThumb: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: "#232527",
  },
  vehiclePickerItemInfo: {
    flex: 1,
  },
  vehiclePickerItemName: {
    color: "#B0B0B0",
    fontSize: 14,
    fontWeight: "500",
  },
  vehiclePickerItemNameActive: {
    color: "#FFFFFF",
    fontWeight: "600",
  },
  vehiclePickerItemPlate: {
    color: "#8E8E93",
    fontSize: 12,
    marginTop: 1,
  },
  vehiclePickerAdd: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginHorizontal: 8,
    marginTop: 6,
    paddingVertical: 11,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(74, 222, 158, 0.2)",
    borderStyle: "dashed",
    backgroundColor: "rgba(74, 222, 158, 0.04)",
  },
  vehiclePickerAddIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: theme.colors.accent.dark,
    alignItems: "center",
    justifyContent: "center",
  },
  vehiclePickerAddText: {
    color: theme.colors.accent.primary,
    fontSize: 14,
    fontWeight: "600",
  },
  pickerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 90,
    elevation: 90,
    backgroundColor: "rgba(0, 0, 0, 0.35)",
  },
  pickerOverlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 90,
    elevation: 90,
    pointerEvents: "box-none",
  },
  heroCard: {
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    backgroundColor: "#1A1C1E",
  },
  heroImage: {
    width: "100%",
    height: 200,
    backgroundColor: "#121212",
  },
  heroPlaceholder: {
    width: "100%",
    height: 200,
    backgroundColor: theme.colors.accent.dark,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  heroPlaceholderLabel: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "500",
  },
  heroOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingVertical: 6,
    backgroundColor: "rgba(0, 0, 0, 0.55)",
  },
  heroBrand: {
    color: "#B0B0B0",
    fontSize: 12,
    fontWeight: "500",
    marginBottom: 2,
  },
  heroModel: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "700",
  },
  plateBadge: {
    position: "absolute",
    top: 12,
    right: 12,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 6,
    borderLeftWidth: 3,
    borderLeftColor: "#0057B7",
  },
  plateBadgeText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#121212",
    letterSpacing: 0.5,
  },
  statsRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 14,
  },
  statPill: {
    flex: 1,
    backgroundColor: "#1A1C1E",
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    gap: 4,
  },
  statPillValue: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  statPillLabel: {
    color: "#8E8E93",
    fontSize: 11,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.06)",
  },
  infoRowFirst: {
    borderTopWidth: 0,
    paddingTop: 0,
  },
  infoIcon: {
    marginTop: 1,
  },
  infoContent: {
    flex: 1,
    gap: 2,
  },
  infoLabel: {
    color: "#8E8E93",
    fontSize: 12,
  },
  infoValue: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "500",
  },
  infoValueRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  colorSwatch: {
    width: 18,
    height: 18,
    borderRadius: 4,
    marginRight: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
  },
  colorValueRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  historyList: {
    gap: 10,
  },
  historyCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.04)",
  },
  historyAvatar: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: theme.colors.accent.dark,
    alignItems: "center",
    justifyContent: "center",
  },
  historyContent: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  historyTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  historyTitle: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
    flex: 1,
  },
  historyDate: {
    color: "#8E8E93",
    fontSize: 12,
  },
  historyDesc: {
    color: "#B0B0B0",
    fontSize: 13,
    lineHeight: 18,
  },
  emptyHistoryText: {
    color: "#8E8E93",
    fontSize: 14,
    lineHeight: 20,
  },
  emptyGarageCard: {
    backgroundColor: "#1A1C1E",
    borderRadius: 16,
    padding: 32,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    borderStyle: "dashed",
    gap: 8,
  },
  emptyGarageTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  emptyGarageText: {
    color: "#8E8E93",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 8,
  },
  emptyGarageButton: {
    backgroundColor: theme.colors.accent.dark,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 18,
    marginTop: 4,
  },
  emptyGarageButtonText: {
    color: theme.colors.accent.primary,
    fontSize: 14,
    fontWeight: "600",
  },
  carLoading: {
    paddingVertical: 40,
    alignItems: "center",
    gap: 10,
  },
  carLoadingText: {
    color: "#8E8E93",
    fontSize: 14,
  },
  quickActions: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 14,
  },
  quickAction: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: theme.colors.accent.dark,
    borderRadius: 12,
    paddingVertical: 11,
  },
  quickActionText: {
    color: theme.colors.accent.primary,
    fontSize: 13,
    fontWeight: "600",
  },
});
