import { StyleSheet } from "react-native";
import { theme } from "../../styles/theme";

export const styles = StyleSheet.create({
  contentContainer: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 24,
  },
  pageTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 4,
  },
  pageSubtitle: {
    color: "#8E8E93",
    fontSize: 14,
    marginBottom: 14,
    lineHeight: 20,
  },
  serviceBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "flex-start",
    backgroundColor: "rgba(74, 222, 158, 0.1)",
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginBottom: 18,
  },
  serviceBadgeText: {
    color: theme.colors.accent.primary,
    fontSize: 13,
    fontWeight: "500",
    flexShrink: 1,
  },
  section: {
    backgroundColor: "#1A1C1E",
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    gap: 12,
  },
  sectionTitle: {
    color: theme.colors.accent.primary,
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  sectionHint: {
    color: "#8E8E93",
    fontSize: 12,
    lineHeight: 17,
    marginTop: -4,
  },
  vehicleCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    padding: 12,
    gap: 8,
  },
  vehicleCardSelected: {
    borderColor: "rgba(74, 222, 158, 0.35)",
    backgroundColor: "rgba(74, 222, 158, 0.06)",
  },
  vehicleCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  vehicleCardTitle: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
    flex: 1,
  },
  vehicleCardPlate: {
    color: theme.colors.accent.primary,
    fontSize: 12,
    fontWeight: "600",
    backgroundColor: theme.colors.accent.dark,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  vehicleMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  vehicleMetaPill: {
    color: "#B0B0B0",
    fontSize: 12,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  reasonCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    padding: 12,
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
  },
  reasonCardSelected: {
    borderColor: "rgba(74, 222, 158, 0.35)",
    backgroundColor: "rgba(74, 222, 158, 0.06)",
  },
  reasonIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: theme.colors.accent.dark,
    alignItems: "center",
    justifyContent: "center",
  },
  reasonIconWrapSelected: {
    backgroundColor: "rgba(74, 222, 158, 0.2)",
  },
  reasonContent: {
    flex: 1,
    gap: 2,
  },
  reasonTitle: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  reasonSubtitle: {
    color: "#8E8E93",
    fontSize: 12,
    lineHeight: 17,
  },
  field: {
    gap: 6,
  },
  label: {
    color: "#8E8E93",
    fontSize: 13,
  },
  textarea: {
    backgroundColor: "#232527",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    color: "#FFFFFF",
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 15,
    minHeight: 110,
    textAlignVertical: "top",
  },
  mediaToolbar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 4,
  },
  mediaButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: theme.colors.accent.dark,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "rgba(74, 222, 158, 0.15)",
  },
  mediaButtonText: {
    color: theme.colors.accent.primary,
    fontSize: 12,
    fontWeight: "600",
  },
  attachmentsList: {
    gap: 8,
    marginTop: 4,
  },
  attachmentItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  attachmentLabel: {
    color: "#FFFFFF",
    fontSize: 13,
    flex: 1,
  },
  attachmentRemove: {
    padding: 4,
  },
  dayPickerContent: {
    gap: 8,
    paddingVertical: 2,
  },
  dayChip: {
    width: 68,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 6,
    gap: 2,
  },
  dayChipSelected: {
    borderColor: "rgba(74, 222, 158, 0.4)",
    backgroundColor: "rgba(74, 222, 158, 0.12)",
  },
  dayWeekday: {
    color: "#8E8E93",
    fontSize: 11,
    textTransform: "capitalize",
  },
  dayNumber: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
  },
  dayMonth: {
    color: "#8E8E93",
    fontSize: 11,
    textTransform: "capitalize",
  },
  dayTextSelected: {
    color: theme.colors.accent.primary,
  },
  slotRow: {
    flexDirection: "row",
    gap: 8,
  },
  slotChip: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    paddingVertical: 10,
    paddingHorizontal: 8,
    alignItems: "center",
    gap: 2,
  },
  slotChipSelected: {
    borderColor: "rgba(74, 222, 158, 0.35)",
    backgroundColor: "rgba(74, 222, 158, 0.1)",
  },
  slotLabel: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "600",
  },
  slotLabelSelected: {
    color: theme.colors.accent.primary,
  },
  slotRange: {
    color: "#8E8E93",
    fontSize: 11,
    textAlign: "center",
  },
  partsCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    padding: 12,
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
  },
  partsCardSelected: {
    borderColor: "rgba(74, 222, 158, 0.35)",
    backgroundColor: "rgba(74, 222, 158, 0.06)",
  },
  partsRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  partsRadioSelected: {
    borderColor: theme.colors.accent.primary,
  },
  partsRadioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: theme.colors.accent.primary,
  },
  partsTitle: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  partsSubtitle: {
    color: "#8E8E93",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },
  actionsSection: {
    gap: 10,
    marginTop: 4,
    marginBottom: 8,
  },
  submitButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: theme.colors.interactive.primary,
    borderRadius: 14,
    paddingVertical: 14,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    color: theme.colors.text.inverse,
    fontSize: 15,
    fontWeight: "600",
  },
  cancelButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: theme.colors.accent.dark,
    borderRadius: 14,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "rgba(74, 222, 158, 0.15)",
  },
  cancelButtonText: {
    color: theme.colors.accent.primary,
    fontSize: 15,
    fontWeight: "600",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
    gap: 12,
  },
  emptyCard: {
    alignItems: "center",
    gap: 10,
    paddingVertical: 8,
  },
  emptyText: {
    color: "#8E8E93",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },
  addCarButton: {
    marginTop: 4,
    backgroundColor: theme.colors.interactive.primary,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  addCarButtonText: {
    color: theme.colors.text.inverse,
    fontSize: 14,
    fontWeight: "600",
  },
});
