import { StyleSheet } from "react-native";
import { theme } from "../../styles/theme";

export const styles = StyleSheet.create({
  scroll: {
    flex: 1,
  },
  panel: {
    flex: 1,
    position: "relative",
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingBottom: 28,
  },
  scrollContent: {
    paddingTop: 16,
  },
  pageTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 4,
  },
  pageSubtitle: {
    color: "#8E8E93",
    fontSize: 14,
    marginBottom: 14,
    lineHeight: 20,
  },
  vehicleBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "flex-start",
    backgroundColor: "rgba(74, 222, 158, 0.1)",
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginBottom: 16,
  },
  vehicleBadgeText: {
    color: theme.colors.accent.primary,
    fontSize: 13,
    fontWeight: "500",
  },
  topActions: {
    marginBottom: 16,
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: theme.colors.accent.dark,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "rgba(74, 222, 158, 0.15)",
  },
  addButtonText: {
    color: theme.colors.accent.primary,
    fontSize: 14,
    fontWeight: "600",
  },
  listSection: {
    gap: 12,
  },
  visitCard: {
    backgroundColor: "#1A1C1E",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  visitCardInner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  visitCardFullWidth: {
    width: "100%",
    marginTop: 12,
  },
  visitAvatar: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: theme.colors.accent.dark,
    alignItems: "center",
    justifyContent: "center",
  },
  visitMain: {
    flex: 1,
    minWidth: 0,
  },
  visitBody: {
    width: "100%",
  },
  expandableContent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
  },
  swipeActions: {
    flexDirection: "row",
    alignItems: "stretch",
    marginBottom: 12,
    marginLeft: 8,
    gap: 8,
  },
  swipeEditAction: {
    width: 80,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 8,
    backgroundColor: theme.colors.accent.dark,
    borderWidth: 1,
    borderColor: "rgba(74, 222, 158, 0.22)",
  },
  swipeDeleteAction: {
    width: 80,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 8,
    backgroundColor: "rgba(248, 81, 73, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(248, 81, 73, 0.28)",
  },
  swipeActionText: {
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
  },
  swipeEditActionText: {
    color: theme.colors.accent.primary,
  },
  swipeDeleteActionText: {
    color: "#F85149",
  },
  swipeableWrapper: {
    marginBottom: 0,
  },
  visitHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 6,
  },
  visitTitle: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
    flex: 1,
  },
  visitDate: {
    color: "#8E8E93",
    fontSize: 12,
  },
  visitDescription: {
    color: "#B0B0B0",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 10,
  },
  worksSection: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.04)",
    width: "100%",
    alignSelf: "stretch",
  },
  worksTitle: {
    color: theme.colors.accent.primary,
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 10,
  },
  workRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.06)",
    gap: 12,
  },
  workRowFirst: {
    borderTopWidth: 0,
    paddingTop: 0,
  },
  workName: {
    color: "#FFFFFF",
    fontSize: 14,
    flex: 1,
  },
  workPrice: {
    color: "#8E8E93",
    fontSize: 13,
    fontWeight: "500",
  },
  workTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 10,
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: "rgba(74, 222, 158, 0.15)",
    gap: 12,
  },
  workTotalLabel: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  workTotalPrice: {
    color: theme.colors.accent.primary,
    fontSize: 15,
    fontWeight: "700",
  },
  emptyCard: {
    backgroundColor: "#1A1C1E",
    borderRadius: 16,
    padding: 32,
    alignItems: "center",
    marginTop: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    borderStyle: "dashed",
    gap: 8,
  },
  emptyTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  emptyText: {
    color: "#8E8E93",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 8,
  },
  emptyWorksText: {
    color: "#8E8E93",
    fontSize: 13,
    lineHeight: 18,
  },
  detailsButton: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
    gap: 6,
    backgroundColor: theme.colors.accent.dark,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "rgba(74, 222, 158, 0.15)",
    minHeight: 34,
    minWidth: 118,
    justifyContent: "center",
  },
  detailsButtonText: {
    color: theme.colors.accent.primary,
    fontSize: 13,
    fontWeight: "600",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
    gap: 8,
  },
  retryButton: {
    marginTop: 12,
  },
});
