import { StyleSheet } from "react-native";
import { theme } from "../../styles/theme";

export const styles = StyleSheet.create({
  scroll: {
    flex: 1,
  },
  panel: {
    flex: 1,
    position: "relative",
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingBottom: 28,
  },
  scrollContent: {
    paddingTop: 16,
  },
  pageTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 4,
  },
  pageSubtitle: {
    color: "#8E8E93",
    fontSize: 14,
    marginBottom: 12,
  },
  topActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginBottom: 14,
  },
  addButton: {
    backgroundColor: theme.colors.accent.dark,
    borderRadius: 10,
    paddingVertical: 9,
    paddingHorizontal: 12,
  },
  addButtonText: {
    color: theme.colors.accent.primary,
    fontSize: 13,
    fontWeight: "600",
  },
  visitCard: {
    backgroundColor: "#1A1C1E",
    borderRadius: 16,
    padding: 16,
  },
  expandableContent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
  },
  swipeActions: {
    flexDirection: "row",
    alignItems: "flex-start",
    alignSelf: "flex-start",
    marginBottom: 14,
    marginLeft: 8,
  },
  swipeEditAction: {
    width: 88,
    height: 108,
    backgroundColor: "#2563EB",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 8,
  },
  swipeDeleteAction: {
    width: 88,
    height: 108,
    backgroundColor: "#DC2626",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 8,
    marginLeft: 8,
  },
  swipeActionText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
  },
  swipeableWrapper: {
    marginBottom: 14,
  },
  visitHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
    gap: 8,
  },
  visitTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    flex: 1,
  },
  visitDate: {
    color: "#8E8E93",
    fontSize: 12,
  },
  visitDescription: {
    color: "#B0B0B0",
    fontSize: 14,
    marginBottom: 10,
  },
  worksTitle: {
    color: theme.colors.accent.primary,
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 8,
  },
  workRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 7,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
    gap: 12,
  },
  workName: {
    color: "#FFFFFF",
    fontSize: 14,
    flex: 1,
  },
  workPrice: {
    color: "#8E8E93",
    fontSize: 13,
  },
  workTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 10,
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.12)",
    gap: 12,
  },
  workTotalLabel: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  workTotalPrice: {
    color: theme.colors.accent.primary,
    fontSize: 15,
    fontWeight: "700",
  },
  emptyCard: {
    backgroundColor: "#1A1C1E",
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    marginTop: 16,
  },
  emptyTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 6,
  },
  emptyText: {
    color: "#8E8E93",
    fontSize: 14,
    textAlign: "center",
  },
  emptyWorksText: {
    color: "#8E8E93",
    fontSize: 14,
    marginBottom: 4,
  },
  detailsButton: {
    alignSelf: "flex-start",
    marginTop: 12,
    backgroundColor: "rgba(74, 222, 158, 0.12)",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 14,
    minWidth: 118,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 34,
  },
  detailsButtonText: {
    color: theme.colors.accent.primary,
    fontSize: 13,
    fontWeight: "600",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  retryButton: {
    marginTop: 16,
  },
});
