import { StyleSheet } from "react-native";
import { theme } from "../../styles/theme";

export const styles = StyleSheet.create({
  panel: {
    flex: 1,
    position: "relative",
  },
  scroll: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingBottom: 28,
  },
  scrollContent: {
    paddingTop: 16,
    gap: 14,
  },
  pageTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 4,
  },
  pageSubtitle: {
    color: "#8E8E93",
    fontSize: 14,
    marginBottom: 14,
    lineHeight: 20,
  },
  emptyCard: {
    backgroundColor: "#1A1C1E",
    borderRadius: 16,
    padding: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    alignItems: "center",
    gap: 10,
  },
  emptyTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
  },
  emptyText: {
    color: "#8E8E93",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  section: {
    backgroundColor: "#1A1C1E",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    gap: 12,
  },
  sectionTitle: {
    color: theme.colors.accent.primary,
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  sectionHint: {
    color: "#8E8E93",
    fontSize: 12,
    lineHeight: 17,
    marginTop: -4,
  },
  vehicleCard: {
    gap: 10,
  },
  vehicleHeader: {
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
  },
  vehicleIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: theme.colors.accent.dark,
    alignItems: "center",
    justifyContent: "center",
  },
  vehicleInfo: {
    flex: 1,
    gap: 3,
  },
  vehicleTitle: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "600",
  },
  vehicleMeta: {
    color: "#8E8E93",
    fontSize: 13,
  },
  problemText: {
    color: "#B0B0B0",
    fontSize: 13,
    lineHeight: 18,
  },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  progressLabel: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  progressPercent: {
    color: theme.colors.accent.primary,
    fontSize: 14,
    fontWeight: "700",
  },
  progressTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 3,
    backgroundColor: theme.colors.accent.primary,
  },
  statusChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  statusChip: {
    borderRadius: 20,
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    backgroundColor: "rgba(255, 255, 255, 0.04)",
  },
  statusChipActive: {
    borderColor: "rgba(74, 222, 158, 0.35)",
    backgroundColor: "rgba(74, 222, 158, 0.12)",
  },
  statusChipText: {
    color: "#B0B0B0",
    fontSize: 12,
    fontWeight: "600",
  },
  statusChipTextActive: {
    color: theme.colors.accent.primary,
  },
  timelineRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 4,
    marginTop: 4,
  },
  timelineStep: {
    flex: 1,
    alignItems: "center",
    gap: 6,
  },
  timelineConnector: {
    position: "absolute",
    top: 5,
    left: "50%",
    right: "-50%",
    height: 2,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    zIndex: 0,
  },
  timelineConnectorDone: {
    backgroundColor: "rgba(74, 222, 158, 0.35)",
  },
  timelineDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.15)",
    zIndex: 1,
  },
  timelineDotDone: {
    backgroundColor: theme.colors.accent.primary,
    borderColor: theme.colors.accent.primary,
  },
  timelineDotActive: {
    backgroundColor: "#1A1C1E",
    borderColor: theme.colors.accent.primary,
    borderWidth: 2,
  },
  timelineLabel: {
    color: "#8E8E93",
    fontSize: 9,
    fontWeight: "600",
    textAlign: "center",
    lineHeight: 12,
  },
  timelineLabelActive: {
    color: theme.colors.accent.primary,
  },
  timelineLabelDone: {
    color: "#B0B0B0",
  },
  stageInfoCard: {
    backgroundColor: "rgba(74, 222, 158, 0.06)",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(74, 222, 158, 0.15)",
    gap: 4,
  },
  stageInfoTitle: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
  },
  stageInfoText: {
    color: "#B0B0B0",
    fontSize: 13,
    lineHeight: 18,
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  priceInput: {
    flex: 1,
    minWidth: 80,
  },
  priceSuffix: {
    color: "#8E8E93",
    fontSize: 13,
    fontWeight: "600",
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.06)",
  },
  totalLabel: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  totalValue: {
    color: theme.colors.accent.primary,
    fontSize: 16,
    fontWeight: "700",
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: theme.colors.interactive.primary,
    borderRadius: 14,
    paddingVertical: 14,
    marginTop: 4,
  },
  primaryButtonText: {
    color: theme.colors.text.inverse,
    fontSize: 15,
    fontWeight: "600",
  },
  secondaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    borderRadius: 14,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
  },
  secondaryButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
  },
  actionGroup: {
    gap: 10,
  },
  partOrderItem: {
    borderColor: "rgba(255, 166, 87, 0.2)",
    backgroundColor: "rgba(255, 166, 87, 0.04)",
  },
  partsInfoCard: {
    backgroundColor: "rgba(255, 166, 87, 0.08)",
    borderColor: "rgba(255, 166, 87, 0.2)",
  },
  partMetaRow: {
    flexDirection: "row",
    gap: 8,
  },
  partMetaInput: {
    width: 72,
    flexGrow: 0,
    flexShrink: 0,
  },
  partMetaInputWide: {
    flex: 1,
  },
  completedCard: {
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
  },
  completedTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
  },
  estimateStatusBadge: {
    alignSelf: "flex-start",
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderWidth: 1,
  },
  estimateStatusText: {
    fontSize: 11,
    fontWeight: "600",
  },
  input: {
    backgroundColor: "#232527",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    color: "#FFFFFF",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  textarea: {
    minHeight: 100,
    textAlignVertical: "top",
  },
  photoToolbar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  photoButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: theme.colors.accent.dark,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "rgba(74, 222, 158, 0.15)",
  },
  photoButtonText: {
    color: theme.colors.accent.primary,
    fontSize: 12,
    fontWeight: "600",
  },
  photoList: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  photoThumbWrap: {
    position: "relative",
  },
  photoThumb: {
    width: 72,
    height: 72,
    borderRadius: 10,
    backgroundColor: "#232527",
  },
  photoRemove: {
    position: "absolute",
    top: -6,
    right: -6,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#1A1C1E",
    borderWidth: 1,
    borderColor: "rgba(248, 81, 73, 0.5)",
    alignItems: "center",
    justifyContent: "center",
  },
  workItem: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    padding: 12,
    gap: 10,
  },
  workItemRecommended: {
    borderColor: "rgba(255, 166, 87, 0.25)",
    backgroundColor: "rgba(255, 166, 87, 0.05)",
  },
  workItemHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  workItemBadges: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  kindBadge: {
    borderRadius: 8,
    paddingVertical: 3,
    paddingHorizontal: 8,
    backgroundColor: "rgba(255, 166, 87, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(255, 166, 87, 0.25)",
  },
  kindBadgeText: {
    color: "#FFA657",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  approvalBadge: {
    borderRadius: 8,
    paddingVertical: 3,
    paddingHorizontal: 8,
    backgroundColor: "rgba(210, 153, 34, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(210, 153, 34, 0.25)",
  },
  approvalBadgeText: {
    color: "#D29922",
    fontSize: 10,
    fontWeight: "700",
  },
  removeWorkButton: {
    padding: 4,
  },
  statusRow: {
    flexDirection: "row",
    gap: 6,
  },
  statusToggle: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 6,
    borderWidth: 1,
    alignItems: "center",
  },
  statusToggleText: {
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: theme.colors.accent.dark,
    borderRadius: 12,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: "rgba(74, 222, 158, 0.15)",
    borderStyle: "dashed",
  },
  addButtonText: {
    color: theme.colors.accent.primary,
    fontSize: 14,
    fontWeight: "600",
  },
  recommendButton: {
    borderColor: "rgba(255, 166, 87, 0.25)",
    backgroundColor: "rgba(255, 166, 87, 0.06)",
  },
  recommendButtonText: {
    color: "#FFA657",
  },
  saveButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: theme.colors.interactive.primary,
    borderRadius: 14,
    paddingVertical: 14,
    marginTop: 4,
  },
  saveButtonText: {
    color: theme.colors.text.inverse,
    fontSize: 15,
    fontWeight: "600",
  },
});
